/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  File name: ddsperf_types.c
  Source: ddsperf_types.idl
  Cyclone DDS: V0.5.0

*****************************************************************/
#include "ddsperf_types.h"


static const uint32_t OneULong_ops [] =
{
  DDS_OP_ADR | DDS_OP_TYPE_4BY, offsetof (OneULong, seq),
  DDS_OP_RTS
};

const dds_topic_descriptor_t OneULong_desc =
{
  sizeof (OneULong),
  4u,
  0u,
  0u,
  "OneULong",
  NULL,
  2,
  OneULong_ops,
  "<MetaData version=\"1.0.0\"><Struct name=\"OneULong\"><Member name=\"seq\"><ULong/></Member></Struct></MetaData>"
};


static const uint32_t Unkeyed16_ops [] =
{
  DDS_OP_ADR | DDS_OP_TYPE_4BY, offsetof (Unkeyed16, seq),
  DDS_OP_ADR | DDS_OP_TYPE_ARR | DDS_OP_SUBTYPE_1BY, offsetof (Unkeyed16, baggage), 12,
  DDS_OP_RTS
};

const dds_topic_descriptor_t Unkeyed16_desc =
{
  sizeof (Unkeyed16),
  4u,
  0u,
  0u,
  "Unkeyed16",
  NULL,
  3,
  Unkeyed16_ops,
  "<MetaData version=\"1.0.0\"><Struct name=\"Unkeyed16\"><Member name=\"seq\"><ULong/></Member><Member name=\"baggage\"><Array size=\"12\"><Octet/></Array></Member></Struct></MetaData>"
};


static const uint32_t Unkeyed1024_ops [] =
{
  DDS_OP_ADR | DDS_OP_TYPE_4BY, offsetof (Unkeyed1024, seq),
  DDS_OP_ADR | DDS_OP_TYPE_ARR | DDS_OP_SUBTYPE_1BY, offsetof (Unkeyed1024, baggage), 1020,
  DDS_OP_RTS
};

const dds_topic_descriptor_t Unkeyed1024_desc =
{
  sizeof (Unkeyed1024),
  4u,
  0u,
  0u,
  "Unkeyed1024",
  NULL,
  3,
  Unkeyed1024_ops,
  "<MetaData version=\"1.0.0\"><Struct name=\"Unkeyed1024\"><Member name=\"seq\"><ULong/></Member><Member name=\"baggage\"><Array size=\"1020\"><Octet/></Array></Member></Struct></MetaData>"
};


static const dds_key_descriptor_t Keyed32_keys[1] =
{
  { "keyval", 2 }
};

static const uint32_t Keyed32_ops [] =
{
  DDS_OP_ADR | DDS_OP_TYPE_4BY, offsetof (Keyed32, seq),
  DDS_OP_ADR | DDS_OP_TYPE_4BY | DDS_OP_FLAG_KEY, offsetof (Keyed32, keyval),
  DDS_OP_ADR | DDS_OP_TYPE_ARR | DDS_OP_SUBTYPE_1BY, offsetof (Keyed32, baggage), 24,
  DDS_OP_RTS
};

const dds_topic_descriptor_t Keyed32_desc =
{
  sizeof (Keyed32),
  4u,
  DDS_TOPIC_FIXED_KEY,
  1u,
  "Keyed32",
  Keyed32_keys,
  4,
  Keyed32_ops,
  "<MetaData version=\"1.0.0\"><Struct name=\"Keyed32\"><Member name=\"seq\"><ULong/></Member><Member name=\"keyval\"><ULong/></Member><Member name=\"baggage\"><Array size=\"24\"><Octet/></Array></Member></Struct></MetaData>"
};


static const dds_key_descriptor_t Keyed256_keys[1] =
{
  { "keyval", 2 }
};

static const uint32_t Keyed256_ops [] =
{
  DDS_OP_ADR | DDS_OP_TYPE_4BY, offsetof (Keyed256, seq),
  DDS_OP_ADR | DDS_OP_TYPE_4BY | DDS_OP_FLAG_KEY, offsetof (Keyed256, keyval),
  DDS_OP_ADR | DDS_OP_TYPE_ARR | DDS_OP_SUBTYPE_1BY, offsetof (Keyed256, baggage), 248,
  DDS_OP_RTS
};

const dds_topic_descriptor_t Keyed256_desc =
{
  sizeof (Keyed256),
  4u,
  DDS_TOPIC_FIXED_KEY,
  1u,
  "Keyed256",
  Keyed256_keys,
  4,
  Keyed256_ops,
  "<MetaData version=\"1.0.0\"><Struct name=\"Keyed256\"><Member name=\"seq\"><ULong/></Member><Member name=\"keyval\"><ULong/></Member><Member name=\"baggage\"><Array size=\"248\"><Octet/></Array></Member></Struct></MetaData>"
};


static const dds_key_descriptor_t KeyedSeq_keys[1] =
{
  { "keyval", 2 }
};

static const uint32_t KeyedSeq_ops [] =
{
  DDS_OP_ADR | DDS_OP_TYPE_4BY, offsetof (KeyedSeq, seq),
  DDS_OP_ADR | DDS_OP_TYPE_4BY | DDS_OP_FLAG_KEY, offsetof (KeyedSeq, keyval),
  DDS_OP_ADR | DDS_OP_TYPE_SEQ | DDS_OP_SUBTYPE_1BY, offsetof (KeyedSeq, baggage),
  DDS_OP_RTS
};

const dds_topic_descriptor_t KeyedSeq_desc =
{
  sizeof (KeyedSeq),
  sizeof (char *),
  DDS_TOPIC_FIXED_KEY | DDS_TOPIC_NO_OPTIMIZE,
  1u,
  "KeyedSeq",
  KeyedSeq_keys,
  4,
  KeyedSeq_ops,
  "<MetaData version=\"1.0.0\"><Struct name=\"KeyedSeq\"><Member name=\"seq\"><ULong/></Member><Member name=\"keyval\"><ULong/></Member><Member name=\"baggage\"><Sequence><Octet/></Sequence></Member></Struct></MetaData>"
};




static const dds_key_descriptor_t CPUStats_keys[2] =
{
  { "hostname", 0 },
  { "pid", 2 }
};

static const uint32_t CPUStats_ops [] =
{
  DDS_OP_ADR | DDS_OP_TYPE_STR | DDS_OP_FLAG_KEY, offsetof (CPUStats, hostname),
  DDS_OP_ADR | DDS_OP_TYPE_4BY | DDS_OP_FLAG_KEY, offsetof (CPUStats, pid),
  DDS_OP_ADR | DDS_OP_TYPE_8BY, offsetof (CPUStats, maxrss),
  DDS_OP_ADR | DDS_OP_TYPE_4BY, offsetof (CPUStats, vcsw),
  DDS_OP_ADR | DDS_OP_TYPE_4BY, offsetof (CPUStats, ivcsw),
  DDS_OP_ADR | DDS_OP_TYPE_BOO, offsetof (CPUStats, some_above),
  DDS_OP_ADR | DDS_OP_TYPE_SEQ | DDS_OP_SUBTYPE_STU, offsetof (CPUStats, cpu),
  sizeof (CPUStatThread), (11u << 16u) + 4u,
  DDS_OP_ADR | DDS_OP_TYPE_STR, offsetof (CPUStatThread, name),
  DDS_OP_ADR | DDS_OP_TYPE_4BY, offsetof (CPUStatThread, u_pct),
  DDS_OP_ADR | DDS_OP_TYPE_4BY, offsetof (CPUStatThread, s_pct),
  DDS_OP_RTS,
  DDS_OP_RTS
};

const dds_topic_descriptor_t CPUStats_desc =
{
  sizeof (CPUStats),
  8u,
  DDS_TOPIC_NO_OPTIMIZE,
  2u,
  "CPUStats",
  CPUStats_keys,
  13,
  CPUStats_ops,
  "<MetaData version=\"1.0.0\"><Struct name=\"CPUStatThread\"><Member name=\"name\"><String/></Member><Member name=\"u_pct\"><Long/></Member><Member name=\"s_pct\"><Long/></Member></Struct><Struct name=\"CPUStats\"><Member name=\"hostname\"><String/></Member><Member name=\"pid\"><ULong/></Member><Member name=\"maxrss\"><Double/></Member><Member name=\"vcsw\"><ULong/></Member><Member name=\"ivcsw\"><ULong/></Member><Member name=\"some_above\"><Boolean/></Member><Member name=\"cpu\"><Sequence><Type name=\"CPUStatThread\"/></Sequence></Member></Struct></MetaData>"
};
