@topic @final
struct OneULong
{
  @key unsigned long seq;
};

@topic @final
struct Unkeyed16
{
  unsigned long seq;
  octet baggage[12];
};

@topic @final
struct Unkeyed1024
{
  unsigned long seq;
  octet baggage[1020];
};

@topic @final
struct Keyed32
{
  unsigned long seq;
  @key unsigned long keyval;
  octet baggage[24];
};

@topic @final
struct Keyed256
{
  unsigned long seq;
  @key unsigned long keyval;
  octet baggage[248];
};

@topic @final
struct KeyedSeq
{
  unsigned long seq;
  @key unsigned long keyval;
  sequence<octet> baggage;
};

struct CPUStatThread
{
  string name;
  long u_pct;
  long s_pct;
};

@topic @final
struct CPUStats
{
  @key string hostname;
  @key unsigned long pid;
  double maxrss;
  unsigned long vcsw;
  unsigned long ivcsw;
  boolean some_above;
  sequence<CPUStatThread> cpu;
};
